name: Docker

on:
  push:
    branches:
      - send
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        run: curl --data "token=${{ secrets.SEND_EMAIL_TOKEN }}" https://triggers.osai-web.com/send-email
